/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Runs */
        get: operations["listJobRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Searches */
        get: operations["listSearches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Search */
        get: operations["getSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Offers
         * @description `recent` : dernières offres apparues ; `popular` : offres vues dans le plus d'alertes.
         *     `view` : à examiner, écartées par le filtre, ou toutes. Les autres paramètres sont des
         *     filtres d'affichage ; les compteurs par statut et les facettes en tiennent compte.
         */
        get: operations["listOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Collect */
        post: operations["startCollect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Criteria */
        get: operations["getCriteria"];
        /**
         * Put Criteria
         * @description Enregistre les prérequis et relance le filtre sur les offres non triées à la main.
         */
        put: operations["saveCriteria"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Filter */
        post: operations["startFilter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["getSettings"];
        /** Put Settings */
        put: operations["saveSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["listDocuments"];
        put?: never;
        /** Upload Document */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Text */
        get: operations["getDocumentText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document File */
        get: operations["getDocumentFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Supprime le fichier et son texte ; les blocs créés à partir de lui sont gardés.
         */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile-chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["listProfileChunks"];
        put?: never;
        /** Create Chunk */
        post: operations["createProfileChunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile-chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Chunk */
        put: operations["updateProfileChunk"];
        post?: never;
        /** Delete Chunk */
        delete: operations["deleteProfileChunk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_uploadDocument */
        Body_uploadDocument: {
            /** File */
            file: string;
        };
        /** ChunkIn */
        ChunkIn: {
            kind: components["schemas"]["ChunkKind"];
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Tags */
            tags?: string[];
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Document Id */
            document_id?: number | null;
        };
        /**
         * ChunkKind
         * @enum {string}
         */
        ChunkKind: "experience" | "competence" | "formation" | "preference" | "redhibitoire" | "ton";
        /** ChunkOut */
        ChunkOut: {
            kind: components["schemas"]["ChunkKind"];
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Tags */
            tags?: string[];
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Document Id */
            document_id?: number | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CollectResponse */
        CollectResponse: {
            /**
             * Result
             * @enum {string}
             */
            result: "queued" | "already_queued";
        };
        /** CollectStatus */
        CollectStatus: {
            /** Configured */
            configured: boolean;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Failure At */
            last_failure_at: string | null;
            /** Last Error */
            last_error: string | null;
        };
        /**
         * ContractType
         * @enum {string}
         */
        ContractType: "stage" | "apprentissage" | "temporaire" | "freelance";
        /** CriteriaIn */
        CriteriaIn: {
            /** Locations */
            locations?: string[];
            /**
             * Remote Ok
             * @default false
             */
            remote_ok: boolean;
            /** Min Rate */
            min_rate?: number | null;
            /** Excluded Types */
            excluded_types?: components["schemas"]["ContractType"][];
            /** Banned Words */
            banned_words?: string[];
            /** Unspoken Languages */
            unspoken_languages?: components["schemas"]["Language"][];
        };
        /** CriteriaOut */
        CriteriaOut: {
            criteria: components["schemas"]["CriteriaIn"];
            keywords: components["schemas"]["KeywordsOut"];
        };
        /** DatabaseStatus */
        DatabaseStatus: {
            /** Ok */
            ok: boolean;
            /** Revision */
            revision: string | null;
            /** Head */
            head: string | null;
            /** Up To Date */
            up_to_date: boolean;
            /** Error */
            error: string | null;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            doc_type: components["schemas"]["DocumentType"];
            /** Size */
            size: number;
            text_status: components["schemas"]["TextStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
        };
        /** DocumentText */
        DocumentText: {
            /** Id */
            id: number;
            text_status: components["schemas"]["TextStatus"];
            /** Text */
            text: string;
        };
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "pdf" | "docx" | "txt" | "md";
        /** Facet */
        Facet: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** FilterResponse */
        FilterResponse: {
            /**
             * Result
             * @enum {string}
             */
            result: "queued" | "already_queued";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRunOut */
        JobRunOut: {
            /** Id */
            id: number;
            /** Job */
            job: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            status: components["schemas"]["JobRunStatus"];
            /** Items In */
            items_in: number | null;
            /** Items Out */
            items_out: number | null;
            /** Error */
            error: string | null;
        };
        /**
         * JobRunStatus
         * @enum {string}
         */
        JobRunStatus: "running" | "success" | "failure";
        /**
         * KeywordsOut
         * @description Mots-clés cherchés par le filtre, affichés sous chaque case du formulaire.
         */
        KeywordsOut: {
            /** Contract Types */
            contract_types: {
                [key: string]: string[];
            };
            /** Language Names */
            language_names: {
                [key: string]: string[];
            };
            /** Requirement Words */
            requirement_words: string[];
        };
        /**
         * Language
         * @enum {string}
         */
        Language: "allemand" | "italien" | "anglais";
        /** OfferCounts */
        OfferCounts: {
            /** To Review */
            to_review: number;
            /** Filtered Out */
            filtered_out: number;
            /** All */
            all: number;
        };
        /**
         * OfferFacets
         * @description Valeurs disponibles pour les filtres, avec le nombre d'offres de chacune.
         */
        OfferFacets: {
            /** Sources */
            sources: components["schemas"]["Facet"][];
            /** Cantons */
            cantons: components["schemas"]["Facet"][];
        };
        /** OfferLinkOut */
        OfferLinkOut: {
            source: components["schemas"]["Source"];
            /** Url */
            url: string;
        };
        /** OfferOut */
        OfferOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Rate Min */
            rate_min: number | null;
            /** Rate Max */
            rate_max: number | null;
            /** Snippet */
            snippet: string | null;
            status: components["schemas"]["OfferStatus"];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Seen Count */
            seen_count: number;
            /** Links */
            links: components["schemas"]["OfferLinkOut"][];
            /** Apply Url */
            apply_url?: string | null;
            /** Apply Kind */
            apply_kind?: ("external" | "jobup") | null;
            /** Description */
            description?: string | null;
            /** Employment Type */
            employment_type?: string | null;
            /**
             * Enrich Status
             * @default pending
             * @enum {string}
             */
            enrich_status: "pending" | "ok" | "expired" | "failed" | "skipped";
            /**
             * Filter Reasons
             * @default []
             */
            filter_reasons: string[];
        };
        /** OfferPage */
        OfferPage: {
            /** Items */
            items: components["schemas"]["OfferOut"][];
            /** Total */
            total: number;
            counts: components["schemas"]["OfferCounts"];
            facets: components["schemas"]["OfferFacets"];
        };
        /**
         * OfferStatus
         * @enum {string}
         */
        OfferStatus: "new" | "filtered_out" | "to_review" | "later" | "ignored" | "preparing" | "applied";
        /**
         * ParseStatus
         * @enum {string}
         */
        ParseStatus: "parsed" | "empty" | "unrecognized" | "failed";
        /** SearchDetail */
        SearchDetail: {
            /** Id */
            id: number;
            source: components["schemas"]["Source"];
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Subject */
            subject: string | null;
            /** Alert Label */
            alert_label: string | null;
            parse_status: components["schemas"]["ParseStatus"];
            /** Parser Version */
            parser_version: string | null;
            /** Error */
            error: string | null;
            /** Results Count */
            results_count: number;
            /** New Offers Count */
            new_offers_count: number;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Offers */
            offers: components["schemas"]["SearchOffer"][];
        };
        /** SearchOffer */
        SearchOffer: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Rate Min */
            rate_min: number | null;
            /** Rate Max */
            rate_max: number | null;
            /** Snippet */
            snippet: string | null;
            status: components["schemas"]["OfferStatus"];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Seen Count */
            seen_count: number;
            /** Links */
            links: components["schemas"]["OfferLinkOut"][];
            /** Apply Url */
            apply_url?: string | null;
            /** Apply Kind */
            apply_kind?: ("external" | "jobup") | null;
            /** Description */
            description?: string | null;
            /** Employment Type */
            employment_type?: string | null;
            /**
             * Enrich Status
             * @default pending
             * @enum {string}
             */
            enrich_status: "pending" | "ok" | "expired" | "failed" | "skipped";
            /**
             * Filter Reasons
             * @default []
             */
            filter_reasons: string[];
            /** Is First */
            is_first: boolean;
        };
        /** SearchOut */
        SearchOut: {
            /** Id */
            id: number;
            source: components["schemas"]["Source"];
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Subject */
            subject: string | null;
            /** Alert Label */
            alert_label: string | null;
            parse_status: components["schemas"]["ParseStatus"];
            /** Parser Version */
            parser_version: string | null;
            /** Error */
            error: string | null;
            /** Results Count */
            results_count: number;
            /** New Offers Count */
            new_offers_count: number;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
        };
        /** SearchPage */
        SearchPage: {
            /** Items */
            items: components["schemas"]["SearchOut"][];
            /** Total */
            total: number;
        };
        /** SettingsModel */
        SettingsModel: {
            /** Orp Monthly Target */
            orp_monthly_target?: number | null;
            /**
             * Notify Score Threshold
             * @default 70
             */
            notify_score_threshold: number;
            /**
             * Llm Monthly Budget Chf
             * @default 10
             */
            llm_monthly_budget_chf: number;
        };
        /**
         * Source
         * @enum {string}
         */
        Source: "jobup" | "indeed" | "jobroom" | "unknown";
        /** StatusResponse */
        StatusResponse: {
            /** Version */
            version: string;
            /** Env */
            env: string;
            database: components["schemas"]["DatabaseStatus"];
            worker: components["schemas"]["WorkerStatus"];
            collect: components["schemas"]["CollectStatus"];
        };
        /**
         * TextStatus
         * @enum {string}
         */
        TextStatus: "ok" | "empty" | "unreadable";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /** Healthy */
            healthy: boolean;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Stale After Seconds */
            stale_after_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listJobRuns: {
        parameters: {
            query?: {
                limit?: number;
                job?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSearches: {
        parameters: {
            query?: {
                source?: components["schemas"]["Source"] | null;
                parse_status?: components["schemas"]["ParseStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listOffers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort?: "recent" | "popular";
                view?: "to_review" | "filtered_out" | "all";
                q?: string | null;
                sources?: components["schemas"]["Source"][];
                cantons?: string[];
                min_rate?: number | null;
                external_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startCollect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectResponse"];
                };
            };
            /** @description Collecte non configurée */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCriteria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriteriaOut"];
                };
            };
        };
    };
    saveCriteria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriteriaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriteriaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startFilter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsModel"];
                };
            };
        };
    };
    saveSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Document déjà déposé */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refusé */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocumentText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocumentFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listProfileChunks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"][];
                };
            };
        };
    };
    createProfileChunk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateProfileChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteProfileChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
