/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Runs */
        get: operations["listJobRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DatabaseStatus */
        DatabaseStatus: {
            /** Ok */
            ok: boolean;
            /** Revision */
            revision: string | null;
            /** Head */
            head: string | null;
            /** Up To Date */
            up_to_date: boolean;
            /** Error */
            error: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRunOut */
        JobRunOut: {
            /** Id */
            id: number;
            /** Job */
            job: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            status: components["schemas"]["JobRunStatus"];
            /** Items In */
            items_in: number | null;
            /** Items Out */
            items_out: number | null;
            /** Error */
            error: string | null;
        };
        /**
         * JobRunStatus
         * @enum {string}
         */
        JobRunStatus: "running" | "success" | "failure";
        /** StatusResponse */
        StatusResponse: {
            /** Version */
            version: string;
            /** Env */
            env: string;
            database: components["schemas"]["DatabaseStatus"];
            worker: components["schemas"]["WorkerStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /** Healthy */
            healthy: boolean;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Stale After Seconds */
            stale_after_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listJobRuns: {
        parameters: {
            query?: {
                limit?: number;
                job?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
