/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Runs */
        get: operations["listJobRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Searches */
        get: operations["listSearches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Search */
        get: operations["getSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Offers
         * @description `recent` : dernières offres apparues ; `popular` : offres vues dans le plus d'alertes ;
         *     `score` : meilleure note de l'IA d'abord (offres non notées à la fin).
         *     `view` : à examiner, écartées par le filtre, ou toutes. Les autres paramètres sont des
         *     filtres d'affichage ; les compteurs par statut et les facettes en tiennent compte.
         */
        get: operations["listOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Collect */
        post: operations["startCollect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Criteria */
        get: operations["getCriteria"];
        /**
         * Put Criteria
         * @description Enregistre les prérequis et relance le filtre sur les offres non triées à la main.
         */
        put: operations["saveCriteria"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/filter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Filter */
        post: operations["startFilter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["getSettings"];
        /** Put Settings */
        put: operations["saveSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notifications */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Notification */
        post: operations["testNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["listDocuments"];
        put?: never;
        /** Upload Document */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Text */
        get: operations["getDocumentText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document File */
        get: operations["getDocumentFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Supprime le fichier et son texte ; les blocs créés à partir de lui sont gardés.
         */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/propose-chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Chunks
         * @description L'IA lit le document et propose des blocs. Rien n'est enregistré : c'est l'interface
         *     qui crée les blocs que Kevin accepte.
         */
        post: operations["proposeChunks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile-chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Chunks */
        get: operations["listProfileChunks"];
        put?: never;
        /** Create Chunk */
        post: operations["createProfileChunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile-chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Chunk */
        put: operations["updateProfileChunk"];
        post?: never;
        /** Delete Chunk */
        delete: operations["deleteProfileChunk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoring Status */
        get: operations["getScoringStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Rescore */
        post: operations["startRescore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offer_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Offer Status */
        patch: operations["setOfferStatus"];
        trace?: never;
    };
    "/api/offers/{offer_id}/application-prefill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Application Prefill
         * @description Valeurs proposées pour « Marquer comme envoyée ».
         */
        get: operations["getApplicationPrefill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["listApplications"];
        put?: never;
        /** Create Application */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Applications Summary */
        get: operations["getApplicationsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Application */
        put: operations["updateApplication"];
        post?: never;
        /**
         * Delete Application
         * @description Annule une candidature enregistrée par erreur ; l'offre revient « en préparation ».
         */
        delete: operations["deleteApplication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Identity */
        get: operations["getIdentity"];
        /** Put Identity */
        put: operations["saveIdentity"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationIn */
        ApplicationIn: {
            /**
             * Sent At
             * Format: date
             */
            sent_at: string;
            /** @default electronique */
            method: components["schemas"]["ApplicationMethod"];
            /**
             * Assigned By Orp
             * @default false
             */
            assigned_by_orp: boolean;
            /** Company */
            company: string;
            /** Company Address */
            company_address?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Job Title */
            job_title: string;
            /** Location */
            location?: string | null;
            /** Rate Text */
            rate_text?: string | null;
            /** Offer Id */
            offer_id?: number | null;
        };
        /**
         * ApplicationMethod
         * @description Mode de candidature, au sens du formulaire ORP.
         * @enum {string}
         */
        ApplicationMethod: "electronique" | "ecrit" | "telephone" | "personnel";
        /** ApplicationOut */
        ApplicationOut: {
            /**
             * Sent At
             * Format: date
             */
            sent_at: string;
            /** @default electronique */
            method: components["schemas"]["ApplicationMethod"];
            /**
             * Assigned By Orp
             * @default false
             */
            assigned_by_orp: boolean;
            /** Company */
            company: string;
            /** Company Address */
            company_address?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Job Title */
            job_title: string;
            /** Location */
            location?: string | null;
            /** Rate Text */
            rate_text?: string | null;
            /** @default en_attente */
            status: components["schemas"]["ApplicationStatus"];
            /** Status Reason */
            status_reason?: string | null;
            /** Status At */
            status_at?: string | null;
            /** Interview At */
            interview_at?: string | null;
            /** Id */
            id: number;
            /** Offer Id */
            offer_id: number | null;
            /** Orp Month */
            orp_month: string;
            /** Reminded At */
            reminded_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ApplicationPrefill */
        ApplicationPrefill: {
            /**
             * Sent At
             * Format: date
             */
            sent_at: string;
            /** @default electronique */
            method: components["schemas"]["ApplicationMethod"];
            /**
             * Assigned By Orp
             * @default false
             */
            assigned_by_orp: boolean;
            /** Company */
            company: string;
            /** Company Address */
            company_address?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Job Title */
            job_title: string;
            /** Location */
            location?: string | null;
            /** Rate Text */
            rate_text?: string | null;
            /** Offer Id */
            offer_id: number;
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "en_attente" | "relancee" | "entretien" | "refus" | "engagement" | "sans_reponse";
        /** ApplicationUpdate */
        ApplicationUpdate: {
            /**
             * Sent At
             * Format: date
             */
            sent_at: string;
            /** @default electronique */
            method: components["schemas"]["ApplicationMethod"];
            /**
             * Assigned By Orp
             * @default false
             */
            assigned_by_orp: boolean;
            /** Company */
            company: string;
            /** Company Address */
            company_address?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Contact Phone */
            contact_phone?: string | null;
            /** Job Title */
            job_title: string;
            /** Location */
            location?: string | null;
            /** Rate Text */
            rate_text?: string | null;
            /** @default en_attente */
            status: components["schemas"]["ApplicationStatus"];
            /** Status Reason */
            status_reason?: string | null;
            /** Status At */
            status_at?: string | null;
            /** Interview At */
            interview_at?: string | null;
        };
        /** Body_uploadDocument */
        Body_uploadDocument: {
            /** File */
            file: string;
        };
        /** ChunkIn */
        ChunkIn: {
            kind: components["schemas"]["ChunkKind"];
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Tags */
            tags?: string[];
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Document Id */
            document_id?: number | null;
        };
        /**
         * ChunkKind
         * @enum {string}
         */
        ChunkKind: "experience" | "competence" | "formation" | "preference" | "redhibitoire" | "ton";
        /** ChunkOut */
        ChunkOut: {
            kind: components["schemas"]["ChunkKind"];
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Tags */
            tags?: string[];
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Document Id */
            document_id?: number | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChunkProposal */
        ChunkProposal: {
            kind: components["schemas"]["ChunkKind"];
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Tags */
            tags: string[];
            /** Duplicate Of */
            duplicate_of: number | null;
        };
        /** CollectResponse */
        CollectResponse: {
            /**
             * Result
             * @enum {string}
             */
            result: "queued" | "already_queued";
        };
        /** CollectStatus */
        CollectStatus: {
            /** Configured */
            configured: boolean;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Failure At */
            last_failure_at: string | null;
            /** Last Error */
            last_error: string | null;
        };
        /**
         * ContractType
         * @enum {string}
         */
        ContractType: "stage" | "apprentissage" | "temporaire" | "freelance";
        /** CriteriaIn */
        CriteriaIn: {
            /** Locations */
            locations?: string[];
            /**
             * Remote Ok
             * @default false
             */
            remote_ok: boolean;
            /** Min Rate */
            min_rate?: number | null;
            /** Excluded Types */
            excluded_types?: components["schemas"]["ContractType"][];
            /** Banned Words */
            banned_words?: string[];
            /** Unspoken Languages */
            unspoken_languages?: components["schemas"]["Language"][];
        };
        /** CriteriaOut */
        CriteriaOut: {
            criteria: components["schemas"]["CriteriaIn"];
            keywords: components["schemas"]["KeywordsOut"];
        };
        /** DatabaseStatus */
        DatabaseStatus: {
            /** Ok */
            ok: boolean;
            /** Revision */
            revision: string | null;
            /** Head */
            head: string | null;
            /** Up To Date */
            up_to_date: boolean;
            /** Error */
            error: string | null;
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            doc_type: components["schemas"]["DocumentType"];
            /** Size */
            size: number;
            text_status: components["schemas"]["TextStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
        };
        /** DocumentText */
        DocumentText: {
            /** Id */
            id: number;
            text_status: components["schemas"]["TextStatus"];
            /** Text */
            text: string;
        };
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "pdf" | "docx" | "txt" | "md";
        /** Facet */
        Facet: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** FilterResponse */
        FilterResponse: {
            /**
             * Result
             * @enum {string}
             */
            result: "queued" | "already_queued";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Identity */
        Identity: {
            /** Name */
            name?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
        };
        /** JobRunOut */
        JobRunOut: {
            /** Id */
            id: number;
            /** Job */
            job: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            status: components["schemas"]["JobRunStatus"];
            /** Items In */
            items_in: number | null;
            /** Items Out */
            items_out: number | null;
            /** Error */
            error: string | null;
        };
        /**
         * JobRunStatus
         * @enum {string}
         */
        JobRunStatus: "running" | "success" | "failure";
        /**
         * KeywordsOut
         * @description Mots-clés cherchés par le filtre, affichés sous chaque case du formulaire.
         */
        KeywordsOut: {
            /** Contract Types */
            contract_types: {
                [key: string]: string[];
            };
            /** Language Names */
            language_names: {
                [key: string]: string[];
            };
            /** Requirement Words */
            requirement_words: string[];
        };
        /**
         * Language
         * @enum {string}
         */
        Language: "allemand" | "italien" | "anglais";
        /** MonthSummary */
        MonthSummary: {
            /** Month */
            month: string;
            /** Count */
            count: number;
            /** Target */
            target: number | null;
        };
        /** NotificationsStatus */
        NotificationsStatus: {
            /** Configured */
            configured: boolean;
            /** Server */
            server: string;
        };
        /** OfferCounts */
        OfferCounts: {
            /** To Review */
            to_review: number;
            /** Filtered Out */
            filtered_out: number;
            /** Later */
            later: number;
            /** In Progress */
            in_progress: number;
            /** All */
            all: number;
        };
        /**
         * OfferFacets
         * @description Valeurs disponibles pour les filtres, avec le nombre d'offres de chacune.
         */
        OfferFacets: {
            /** Sources */
            sources: components["schemas"]["Facet"][];
            /** Cantons */
            cantons: components["schemas"]["Facet"][];
        };
        /** OfferLinkOut */
        OfferLinkOut: {
            source: components["schemas"]["Source"];
            /** Url */
            url: string;
        };
        /** OfferOut */
        OfferOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Rate Min */
            rate_min: number | null;
            /** Rate Max */
            rate_max: number | null;
            /** Snippet */
            snippet: string | null;
            status: components["schemas"]["OfferStatus"];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Seen Count */
            seen_count: number;
            /** Links */
            links: components["schemas"]["OfferLinkOut"][];
            /** Apply Url */
            apply_url?: string | null;
            /** Apply Kind */
            apply_kind?: ("external" | "jobup") | null;
            /** Description */
            description?: string | null;
            /** Employment Type */
            employment_type?: string | null;
            /**
             * Enrich Status
             * @default pending
             * @enum {string}
             */
            enrich_status: "pending" | "ok" | "expired" | "failed" | "skipped";
            /**
             * Filter Reasons
             * @default []
             */
            filter_reasons: string[];
            /** Score */
            score?: number | null;
            /** Summary Role */
            summary_role?: string | null;
            /** Summary Asks */
            summary_asks?: string | null;
            /** Summary Offers */
            summary_offers?: string | null;
            /**
             * Summary Partial
             * @default false
             */
            summary_partial: boolean;
            /**
             * Strengths
             * @default []
             */
            strengths: components["schemas"]["ScorePoint"][];
            /**
             * Gaps
             * @default []
             */
            gaps: components["schemas"]["ScorePoint"][];
            /** Scored At */
            scored_at?: string | null;
            /**
             * Score Stale
             * @default false
             */
            score_stale: boolean;
            /** Score Error */
            score_error?: string | null;
        };
        /** OfferPage */
        OfferPage: {
            /** Items */
            items: components["schemas"]["OfferOut"][];
            /** Total */
            total: number;
            counts: components["schemas"]["OfferCounts"];
            facets: components["schemas"]["OfferFacets"];
        };
        /**
         * OfferStatus
         * @enum {string}
         */
        OfferStatus: "new" | "filtered_out" | "to_review" | "later" | "ignored" | "preparing" | "applied";
        /** OfferStatusIn */
        OfferStatusIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "to_review" | "later" | "ignored" | "preparing";
        };
        /** OfferStatusOut */
        OfferStatusOut: {
            /** Id */
            id: number;
            status: components["schemas"]["OfferStatus"];
        };
        /**
         * ParseStatus
         * @enum {string}
         */
        ParseStatus: "parsed" | "empty" | "unrecognized" | "failed";
        /** RescoreResponse */
        RescoreResponse: {
            /**
             * Result
             * @enum {string}
             */
            result: "queued" | "already_queued";
        };
        /** ScorePoint */
        ScorePoint: {
            /** Text */
            text: string;
            /** Chunk Ids */
            chunk_ids: number[];
        };
        /** ScoringStatus */
        ScoringStatus: {
            /** Configured */
            configured: boolean;
            /** Model */
            model: string;
            /** Month Spend Chf */
            month_spend_chf: string;
            /** Budget Chf */
            budget_chf: string;
            /** Budget Reached */
            budget_reached: boolean;
            /** Active Chunks */
            active_chunks: number;
            /** Scored */
            scored: number;
            /** Unscored */
            unscored: number;
            /** Stale */
            stale: number;
            /** Failed */
            failed: number;
            /** Pending Batches */
            pending_batches: number;
            /** Last Error */
            last_error: string | null;
        };
        /** SearchDetail */
        SearchDetail: {
            /** Id */
            id: number;
            source: components["schemas"]["Source"];
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Subject */
            subject: string | null;
            /** Alert Label */
            alert_label: string | null;
            parse_status: components["schemas"]["ParseStatus"];
            /** Parser Version */
            parser_version: string | null;
            /** Error */
            error: string | null;
            /** Results Count */
            results_count: number;
            /** New Offers Count */
            new_offers_count: number;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
            /** Offers */
            offers: components["schemas"]["SearchOffer"][];
        };
        /** SearchOffer */
        SearchOffer: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Location */
            location: string | null;
            /** Rate Min */
            rate_min: number | null;
            /** Rate Max */
            rate_max: number | null;
            /** Snippet */
            snippet: string | null;
            status: components["schemas"]["OfferStatus"];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Seen Count */
            seen_count: number;
            /** Links */
            links: components["schemas"]["OfferLinkOut"][];
            /** Apply Url */
            apply_url?: string | null;
            /** Apply Kind */
            apply_kind?: ("external" | "jobup") | null;
            /** Description */
            description?: string | null;
            /** Employment Type */
            employment_type?: string | null;
            /**
             * Enrich Status
             * @default pending
             * @enum {string}
             */
            enrich_status: "pending" | "ok" | "expired" | "failed" | "skipped";
            /**
             * Filter Reasons
             * @default []
             */
            filter_reasons: string[];
            /** Score */
            score?: number | null;
            /** Summary Role */
            summary_role?: string | null;
            /** Summary Asks */
            summary_asks?: string | null;
            /** Summary Offers */
            summary_offers?: string | null;
            /**
             * Summary Partial
             * @default false
             */
            summary_partial: boolean;
            /**
             * Strengths
             * @default []
             */
            strengths: components["schemas"]["ScorePoint"][];
            /**
             * Gaps
             * @default []
             */
            gaps: components["schemas"]["ScorePoint"][];
            /** Scored At */
            scored_at?: string | null;
            /**
             * Score Stale
             * @default false
             */
            score_stale: boolean;
            /** Score Error */
            score_error?: string | null;
            /** Is First */
            is_first: boolean;
        };
        /** SearchOut */
        SearchOut: {
            /** Id */
            id: number;
            source: components["schemas"]["Source"];
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Subject */
            subject: string | null;
            /** Alert Label */
            alert_label: string | null;
            parse_status: components["schemas"]["ParseStatus"];
            /** Parser Version */
            parser_version: string | null;
            /** Error */
            error: string | null;
            /** Results Count */
            results_count: number;
            /** New Offers Count */
            new_offers_count: number;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
        };
        /** SearchPage */
        SearchPage: {
            /** Items */
            items: components["schemas"]["SearchOut"][];
            /** Total */
            total: number;
        };
        /** SettingsModel */
        SettingsModel: {
            /** Orp Monthly Target */
            orp_monthly_target?: number | null;
            /**
             * Notify Score Threshold
             * @default 70
             */
            notify_score_threshold: number;
            /**
             * Llm Monthly Budget Chf
             * @default 10
             */
            llm_monthly_budget_chf: number;
        };
        /**
         * Source
         * @enum {string}
         */
        Source: "jobup" | "indeed" | "jobroom" | "unknown";
        /** StatusResponse */
        StatusResponse: {
            /** Version */
            version: string;
            /** Env */
            env: string;
            database: components["schemas"]["DatabaseStatus"];
            worker: components["schemas"]["WorkerStatus"];
            collect: components["schemas"]["CollectStatus"];
        };
        /**
         * TextStatus
         * @enum {string}
         */
        TextStatus: "ok" | "empty" | "unreadable";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkerStatus */
        WorkerStatus: {
            /** Healthy */
            healthy: boolean;
            /** Last Heartbeat At */
            last_heartbeat_at: string | null;
            /** Stale After Seconds */
            stale_after_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listJobRuns: {
        parameters: {
            query?: {
                limit?: number;
                job?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSearches: {
        parameters: {
            query?: {
                source?: components["schemas"]["Source"] | null;
                parse_status?: components["schemas"]["ParseStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSearch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listOffers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort?: "recent" | "popular" | "score";
                view?: "to_review" | "filtered_out" | "later" | "in_progress" | "all";
                q?: string | null;
                min_score?: number | null;
                sources?: components["schemas"]["Source"][];
                cantons?: string[];
                min_rate?: number | null;
                external_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startCollect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectResponse"];
                };
            };
            /** @description Collecte non configurée */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCriteria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriteriaOut"];
                };
            };
        };
    };
    saveCriteria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriteriaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriteriaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startFilter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterResponse"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsModel"];
                };
            };
        };
    };
    saveSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsStatus"];
                };
            };
        };
    };
    testNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non configuré */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Envoi refusé */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Document déjà déposé */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refusé */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocumentText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocumentFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proposeChunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkProposal"][];
                };
            };
            /** @description IA non configurée, budget atteint ou compte API indisponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document sans texte lisible */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Réponse de l'IA inutilisable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProfileChunks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"][];
                };
            };
        };
    };
    createProfileChunk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateProfileChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteProfileChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getScoringStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringStatus"];
                };
            };
        };
    };
    startRescore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescoreResponse"];
                };
            };
            /** @description IA non configurée */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setOfferStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferStatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getApplicationPrefill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPrefill"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listApplications: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Candidature déjà enregistrée pour cette offre */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getApplicationsSummary: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
        };
    };
    saveIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Identity"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
